apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset

spec:
  template:
    metadata:
      name: first-pod-dec
      labels:
        app: myapp
        type: restapi
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: restapi
